[phases.setup]
nixPkgs = ["...", "ffmpeg", "yt-dlp"]

[phases.build]
dependsOn = ["setup"]
cmds = ["npm install", "npm run build", "cd server && npm install && npm run build"]

[start]
cmd = "cd server && npm start"
